/**
 * src/lib/cloud-db.ts
 *
 * Neon PostgreSQL connection management and remote schema bootstrap.
 * Server-only module for cloud synchronization.
 */

import { Pool, PoolClient } from 'pg';
import { getSetting } from './db';

const DEFAULT_CLOUD_URL =
  process.env.CLOUD_DATABASE_URL ||
  process.env.DATABASE_URL ||
  'postgresql://neondb_owner:npg_2WfIXydQTn1z@ep-purple-frost-aynhchr1-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require';

let cloudPool: Pool | null = null;
let currentPoolUrl = '';
let schemaBootstrapped = false;

export function getCloudDatabaseUrl(): string {
  try {
    const customUrl = getSetting('cloud_database_url', '').trim();
    if (customUrl && customUrl.startsWith('postgres')) {
      return customUrl;
    }
  } catch (_) {
    // Ignore if db is not ready yet
  }
  return DEFAULT_CLOUD_URL;
}

export function getCloudPool(): Pool {
  const connUrl = getCloudDatabaseUrl();
  if (!cloudPool || currentPoolUrl !== connUrl) {
    if (cloudPool) {
      cloudPool.end().catch(() => {});
    }
    currentPoolUrl = connUrl;
    schemaBootstrapped = false;
    cloudPool = new Pool({
      connectionString: connUrl,
      ssl: {
        rejectUnauthorized: false,
      },
      connectionTimeoutMillis: 8000,
      idleTimeoutMillis: 30000,
      max: 5,
    });
  }
  return cloudPool;
}

export async function testCloudConnection(customUrl?: string): Promise<{ ok: boolean; message: string; version?: string }> {
  const urlToTest = customUrl || getCloudDatabaseUrl();
  if (!urlToTest) {
    return { ok: false, message: 'Cloud database connection URL is not configured.' };
  }

  const tempPool = new Pool({
    connectionString: urlToTest,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 7000,
  });

  try {
    const res = await tempPool.query('SELECT NOW() as now, version() as version');
    const version = res.rows[0]?.version?.split(' ')?.[1] || 'PostgreSQL';
    return {
      ok: true,
      message: `Successfully connected to Neon PostgreSQL (${version})`,
      version,
    };
  } catch (err: unknown) {
    const errMsg = err instanceof Error ? err.message : String(err);
    return { ok: false, message: `Cloud connection failed: ${errMsg}` };
  } finally {
    await tempPool.end().catch(() => {});
  }
}

export async function bootstrapCloudDatabase(client?: PoolClient | Pool): Promise<void> {
  if (schemaBootstrapped && !client) return;
  const runner = client || getCloudPool();

  await runner.query(`
    -- Users & Roles
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      username TEXT UNIQUE NOT NULL,
      password TEXT NOT NULL,
      role TEXT NOT NULL CHECK(role IN ('admin', 'staff')),
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Sessions
    CREATE TABLE IF NOT EXISTS sessions (
      token TEXT PRIMARY KEY,
      user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
      expires_at TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Customers
    CREATE TABLE IF NOT EXISTS customers (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      phone TEXT,
      address TEXT,
      vehicle_number TEXT,
      vehicle_model TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Vehicles
    CREATE TABLE IF NOT EXISTS vehicles (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
      vehicle_number TEXT,
      vehicle_model TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Predefined Services
    CREATE TABLE IF NOT EXISTS predefined_services (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT UNIQUE NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Expense Categories
    CREATE TABLE IF NOT EXISTS expense_categories (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT UNIQUE NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Invoices
    CREATE TABLE IF NOT EXISTS invoices (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      customer_id BIGINT REFERENCES customers(id),
      vehicle_id BIGINT REFERENCES vehicles(id),
      notes TEXT,
      total_amount NUMERIC NOT NULL DEFAULT 0,
      paid_amount NUMERIC NOT NULL DEFAULT 0,
      payment_status TEXT NOT NULL DEFAULT 'unpaid' CHECK(payment_status IN ('unpaid', 'partial', 'paid')),
      payment_method TEXT NOT NULL DEFAULT 'cash' CHECK(payment_method IN ('cash', 'card', 'both', 'other', 'credit')),
      payment_method_note TEXT,
      service_date TEXT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Invoice Items
    CREATE TABLE IF NOT EXISTS invoice_items (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
      description TEXT NOT NULL,
      type TEXT NOT NULL CHECK(type IN ('part', 'labor', 'discount')),
      amount NUMERIC NOT NULL DEFAULT 0,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Expenses
    CREATE TABLE IF NOT EXISTS expenses (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      category_id BIGINT REFERENCES expense_categories(id),
      amount NUMERIC NOT NULL,
      notes TEXT,
      date TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Audit Logs
    CREATE TABLE IF NOT EXISTS audit_logs (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id BIGINT,
      username TEXT NOT NULL,
      action TEXT NOT NULL,
      description TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Settings
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Performance Indexes
    CREATE INDEX IF NOT EXISTS idx_pg_customers_name ON customers(name);
    CREATE INDEX IF NOT EXISTS idx_pg_customers_phone ON customers(phone);
    CREATE INDEX IF NOT EXISTS idx_pg_vehicles_customer_id ON vehicles(customer_id);
    CREATE INDEX IF NOT EXISTS idx_pg_vehicles_number ON vehicles(vehicle_number);
    CREATE INDEX IF NOT EXISTS idx_pg_invoices_customer_id ON invoices(customer_id);
    CREATE INDEX IF NOT EXISTS idx_pg_invoices_service_date ON invoices(service_date);
    CREATE INDEX IF NOT EXISTS idx_pg_invoices_created_at ON invoices(created_at);
    CREATE INDEX IF NOT EXISTS idx_pg_invoice_items_invoice_id ON invoice_items(invoice_id);
    CREATE INDEX IF NOT EXISTS idx_pg_expenses_category_id ON expenses(category_id);
    CREATE INDEX IF NOT EXISTS idx_pg_expenses_date ON expenses(date);
    CREATE INDEX IF NOT EXISTS idx_pg_audit_logs_created_at ON audit_logs(created_at);
  `);

  await runner.query('ALTER TABLE invoices ADD COLUMN IF NOT EXISTS service_date TEXT');
  await runner.query(
    "UPDATE invoices SET service_date = to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD') WHERE service_date IS NULL"
  );

  schemaBootstrapped = true;
}
